generator: admingenerator.generator.doctrine_odm
params:
    model: Julius\RefererBundle\Document\Referer
    namespace_prefix: Julius
    bundle_name: RefererBundle
    fields:
        slug:
            addFormOptions:
                required: false

builders:
    list:
        params:
            title: List for RefererBundle
            display:
                - name
                - slug
                - createdAt
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display:
                - name
                - slug
                - createdAt
    new:
        params:
            title: New object for RefererBundle
            display:
                - name
                - slug
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Referer.name }|"
            display:
                - name
                - slug
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Referer.name }|"
            display:
                - name
                - slug
                - createdAt
            actions:
                list: ~
                new: ~
    actions:
        params:
          object_actions:
              delete: ~
          batch_actions:
              delete: ~
